// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import "dotenv/config";

/**
 * This file is used by Prisma CLI db push, generate, migrations...
 */

// Prisma CLI/migrations should use a direct DB URL, not the Supabase pooler.
const url = process.env.SUPABASE_PROD_DIRECT;
// const url = process.env.DB_URL_DEV;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
