// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import "dotenv/config";

// Currently i disabled strict certificate validation
// Only Enterprise plan users can upload custom ssl
// https://www.prisma.io/docs/orm/prisma-client/deployment/caveats-when-deploying-to-aws-platforms

const currEnv = process.env.NODE_ENV;
console.log(currEnv);

// WARNING: running migration in prod
// const url = process.env.DB_URL_PROD;

const url =
  currEnv === "production" ? process.env.DB_URL_PROD : process.env.DB_URL_TEST;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: url!,
  },
});
